#spring.datasource.driver-class-name: oracle.jdbc.driver.OracleDriver
#spring.datasource.url: jdbc:oracle:thin:@10.33.130.164:1541:ddocs

#spring.datasource.url: jdbc:log4jdbc:oracle:thin:@js-lab.iptime.org:1521:wowsoft
#spring.datasource.url: jdbc:log4jdbc:oracle:thin:@192.168.0.241:1521:esobsoft
#spring.datasource.url: jdbc:log4jdbc:oracle:thin:@localhost:1521:wowsoft
#spring.datasource.url: jdbc:log4jdbc:oracle:thin:@esobinfo.iptime.org:7654:wowsoft

# ?useUnicode=true&characterEncoding=utf8


#spring.datasource.username: docsdev_mgr
#spring.datasource.username: SYSTEM
#spring.datasource.username: ITS_HD
#spring.datasource.password: dhkdn1234
#spring.datasource.password: 1234

#DB??( ORACLE )
# spring.datasource.driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
# spring.datasource.url: jdbc:log4jdbc:oracle:thin:@demo.esob.kr:1521:wowsoft
# spring.datasource.username: fdmsdev_mgr
# spring.datasource.password: dlthq@1234

#KAI demo
# spring.datasource.driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
# spring.datasource.url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
# spring.datasource.username: c##esob
# spring.datasource.password: esob1234

#DB?? ( POSTGRE)
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:postgresql://localhost:5432/kt1b
spring.datasource.username=myuser
spring.datasource.password=1234
# spring.datasource.url=jdbc:log4jdbc:postgresql://10.10.10.195:5432/kt1b
# spring.datasource.username=postgres
# spring.datasource.password=dlthq@1234
#언어팩 확인하기 영문언어팩 등록해야 함

# spring.datasource.url=jdbc:log4jdbc:postgresql://127.0.0.1:5430/collabhub
# spring.datasource.username=collabadmin
# spring.datasource.password=dlthq@1234

#DB?? ( POSTGRE)
# spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
# spring.datasource.url=jdbc:log4jdbc:postgresql://localhost:5432/kari
# spring.datasource.username=postgres
# spring.datasource.password=1234

#DB?? ( POSTGRE)
#spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#spring.datasource.url=jdbc:log4jdbc:postgresql://192.168.0.113:3507/postgres
#spring.datasource.username=postgres
#spring.datasource.password=dlthq@1234

# 뷰 테이블 연동 설정
# pdm.source.db.url=jdbc:log4jdbc:sqlserver://demo.esob.kr:1433;databaseName=interfaceDB;encrypt=false
# pdm.source.db.username=interface_user
# pdm.source.db.password=Qwer1234

# 스케줄러 사용 여부 설정 (true: 활성화, false: 비활성화)
update.distribution.scheduler.enabled=false
file.auto.insert.scheduler.enabled=false
send.mail.scheduler.enabled=false

mybatis.mapper-locations: classpath:/sqlMaps/**/*.xml
#mybatis.configuration.map-underscore-to-camel-case: true
mybatis.config-location: classpath:mybatis-config.xml
spring.mvc.view.prefix: /WEB-INF/views/
spring.mvc.view.suffix: .jsp
spring.mvc.static-path-pattern: /resources/**

spring.mvc.contentnegotiation.media-types.js=application/javascript
spring.resources.chain.strategy.content.enabled=true

spring.mvc.favicon.enabled=false

spring.devtools.livereload.enabled: true
#23.02.13 js캐쉬방지
spring.freemarker.cache=false
spring.thymeleaf.cache=false
#23.02.13 js캐쉬방지

server.tomcat.max-http-post-size: 0
server.tomcat.max-swallow-size: 0
server.servlet.session.timeout: 600s

spring.servlet.multipart.max-file-size: 800MB
spring.servlet.multipart.max-request-size: 800MB

# server.port: 8080
server.port: 3508

# server.port=443
# server.ssl.key-store-type=PKCS12
# server.ssl.key-store=C:/workspaceStartupHub/FMDS/ssl_key/demo.esob.kr-root-chain.p12
# server.ssl.key-store-password=esob@1234
# server.ssl.key-alias=demo.esob.kr

#logging.level.org.springframework=DEBUG
#logging.level.org.apache.coyote.http11=DEBUG
#spring.devtools.restart.enabled=false


#server.port: 443
#server.ssl.key-store: ssl_key/docs.p12
#server.ssl.key-store-password: dhkdn!1234
#server.ssl.key-store-type: PKCS12
#server.ssl.key-alias: DOCS



#log4jdbc.spylogdelegator.name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
#log4jdbc.spylogdelegator.name: com.wowsoft.docs.util.SqlLogUtil

