CREATE TABLE IF NOT EXISTS DOCS_DRAWING_APPROVAL_COMMENT (
    OBJECT_ID    VARCHAR(64)  NOT NULL,
    APPROVER_ID  VARCHAR(100) NOT NULL,
    COMMENT_TXT  VARCHAR(2000),
    UPDATE_DT    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_DOCS_DRAWING_APPROVAL_COMMENT PRIMARY KEY (OBJECT_ID, APPROVER_ID)
);

CREATE INDEX IF NOT EXISTS IDX_DOCS_DRAWING_APPROVAL_COMMENT_01
    ON DOCS_DRAWING_APPROVAL_COMMENT (OBJECT_ID);
