CREATE TABLE IF NOT EXISTS DOCS_PRODUCTION_APPROVAL_COMMENT (
    OBJECT_ID   VARCHAR(64)   NOT NULL,
    APPROVER_ID VARCHAR(128)  NOT NULL,
    COMMENT_TXT VARCHAR(2000),
    UPDATE_DT   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT DOCS_PRODUCTION_APPROVAL_COMMENT_PK PRIMARY KEY (OBJECT_ID, APPROVER_ID)
);

CREATE INDEX IF NOT EXISTS IDX_DOCS_PRODUCTION_APPROVAL_COMMENT_OBJ
    ON DOCS_PRODUCTION_APPROVAL_COMMENT (OBJECT_ID);
